import { type Currency } from '../../../../types/currency';

export const EUR: Currency = {
  code: 'EUR',
  name: 'Euro',
  number: 978,
  minorUnits: 2,
  symbol: '€',
  countries: [
    'ÅLAND ISLANDS',
    'ANDORRA',
    'AUSTRIA',
    'BELGIUM',
    'CROATIA',
    'CYPRUS',
    'ESTONIA',
    'EUROPEAN UNION',
    'FINLAND',
    'FRANCE',
    'FRENCH GUIANA',
    'FRENCH SOUTHERN TERRITORIES (THE)',
    'GERMANY',
    'GREECE',
    'GUADELOUPE',
    'HOLY SEE (THE)',
    'IRELAND',
    'ITALY',
    'LATVIA',
    'LITHUANIA',
    'LUXEMBOURG',
    'MALTA',
    'MARTINIQUE',
    'MAYOTTE',
    'MONACO',
    'MONTENEGRO',
    'NETHERLANDS (THE)',
    'PORTUGAL',
    'RÉUNION',
    'SAINT BARTHÉLEMY',
    'SAINT MARTIN (FRENCH PART)',
    'SAINT PIERRE AND MIQUELON',
    'SAN MARINO',
    'SLOVAKIA',
    'SLOVENIA',
    'SPAIN',
  ],
};
